//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBlog.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBlogFilmEntities : DbContext
    {
        public DBBlogFilmEntities()
            : base("name=DBBlogFilmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLBLOCG> TBLBLOCG { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLCOMMENT> TBLCOMMENT { get; set; }
        public virtual DbSet<TBLELAQE> TBLELAQE { get; set; }
        public virtual DbSet<TBLHAQQIMIZDA> TBLHAQQIMIZDA { get; set; }
        public virtual DbSet<TBLTYPE> TBLTYPE { get; set; }
        public virtual DbSet<TBLADMIN> TBLADMIN { get; set; }
    }
}
