//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmBlog.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLELAQE
    {
        public int MSJID { get; set; }
        public string NAMESURNAME { get; set; }
        public string MAIL { get; set; }
        public string TELEFON { get; set; }
        public string MOVZU { get; set; }
        public string MESAJ { get; set; }
    }
}
